oti-project3/main

.classpath, pom.xml, src/main/java/com/coderby/myapp/attendance/model/AttendanceVO.java, src/main/java/com/coderby/myapp/attendance/model/RequestVO.java, src/main/java/com/coderby/myapp/board/model/BoardVO.java, src/main/java/com/coderby/myapp/board/model/ReplyVO.java, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/java/com/coderby/myapp/classes/dao/IClassRepository.java, src/main/java/com/coderby/myapp/classes/model/ClassVO.java, src/main/java/com/coderby/myapp/classes/model/FileVO.java, src/main/java/com/coderby/myapp/classes/model/SectionVO.java, src/main/java/com/coderby/myapp/classes/model/StudentVO.java, src/main/java/com/coderby/myapp/classes/service/ClassService.java, src/main/java/com/coderby/myapp/classes/service/IClassService.java, src/main/resources/database/jdbc.properties, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/classes/classList.jsp, src/main/webapp/WEB-INF/views/error/runtime.jsp, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml, target/classes/database/jdbc.properties, target/m2e-wtp/web-resources/META-INF/maven/com.coderby/myapp/pom.xml
#1  
classList.jsp 추가
ClassController 수정
ClassService 수정
ClassDao 수정
ClassMapper 추가
=> #1 VO에 GETTER / SETTER 추가

.classpath, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/java/com/coderby/myapp/classes/dao/IClassRepository.java, src/main/java/com/coderby/myapp/classes/model/SectionVO.java, src/main/java/com/coderby/myapp/classes/service/ClassService.java, src/main/java/com/coderby/myapp/classes/service/IClassService.java, src/main/java/com/coderby/myapp/file/dao/FileMapper.xml, src/main/java/com/coderby/myapp/file/dao/IFileRepository.java, src/main/java/com/coderby/myapp/file/model/FileVO.java, src/main/java/com/coderby/myapp/file/service/FileService.java, src/main/java/com/coderby/myapp/file/service/IFileService.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/classes/classList.jsp, src/main/webapp/WEB-INF/views/classes/fileListFragment.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml, target/classes/com/coderby/myapp/file/dao/FileMapper.xml
#1 
sectionVO에 fileList 필드 추가
sectionList.jsp body 주석처리
=> #1 FILE 패키지 생성(각자 도메인에서 사용할 파일 업로드, 파일 다운로드, 파일 삭제, 파일 리스트 조회 기능)

.gitignore, src/main/java/com/coderby/myapp/attendance/model/AttendanceVO.java, src/main/java/com/coderby/myapp/attendance/model/ReportsVO.java, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/controller/ReportsController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/java/com/coderby/myapp/classes/dao/IClassRepository.java, src/main/java/com/coderby/myapp/classes/dao/IReportsRepository.java, src/main/java/com/coderby/myapp/classes/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/classes/service/ClassService.java, src/main/java/com/coderby/myapp/classes/service/IClassService.java, src/main/java/com/coderby/myapp/classes/service/IReportsService.java, src/main/java/com/coderby/myapp/classes/service/ReportsService.java, src/main/webapp/WEB-INF/views/classes/classList.jsp, src/main/webapp/WEB-INF/views/classes/reportsDetail.jsp, src/main/webapp/WEB-INF/views/classes/reportsList.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml, target/classes/com/coderby/myapp/classes/dao/ReportsMapper.xml
#5 
1) 휴가 신청 목록 조회(관리자, 사용자 공용)/ 사용자의 휴가 신청목록 조회는 아직 기능 안 만듬
2) 휴가 상세조회(관리자, 사용자 공용)
3) 휴가 결재(관리자)
=> #5 휴가 목록조회,상세조회,결재  

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/IReportsRepository.java, src/main/java/com/coderby/myapp/attendance/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/attendance/service/IReportsService.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, target/classes/com/coderby/myapp/attendance/dao/ReportsMapper.xml
=> #2 특정학생 휴가 조회

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/AttendanceMapper.xml, src/main/java/com/coderby/myapp/attendance/dao/IAttendanceRepository.java, src/main/java/com/coderby/myapp/attendance/dao/IReportsRepository.java, src/main/java/com/coderby/myapp/attendance/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/attendance/model/AttendanceVO.java, src/main/java/com/coderby/myapp/attendance/model/ReportsVO.java, src/main/java/com/coderby/myapp/attendance/service/AttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/IAttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/IReportsService.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/java/com/coderby/myapp/board/controller/BoardController.java, src/main/java/com/coderby/myapp/classes/controller/StudentController.java, target/classes/com/coderby/myapp/attendance/dao/AttendanceMapper.xml, target/classes/com/coderby/myapp/attendance/dao/ReportsMapper.xml
#5 attendance 정시에 맞춰서 back단 
#5 학생리스트 만들기
=> #2정시에 status 만들기 back단

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/AttendanceMapper.xml, src/main/java/com/coderby/myapp/attendance/dao/IAttendanceRepository.java, src/main/java/com/coderby/myapp/attendance/service/AttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/IAttendanceService.java, src/main/java/com/coderby/myapp/classes/controller/StudentController.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/attendance/attend.jsp, src/main/webapp/WEB-INF/views/example.jsp, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/include/staticFiles.jsp, target/classes/com/coderby/myapp/attendance/dao/AttendanceMapper.xml
#5 attendance 수정
1. jsp 수정
2. lookingStdId 추가
3. mapper 시간 변경 insert
=> #2 attendance

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/controller/StudentController.java, src/main/webapp/WEB-INF/views/attendance/reportsDetail.jsp, src/main/webapp/WEB-INF/views/attendance/studentReportsList.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/attendance/dao/ReportsMapper.xml
=> #5 aafafaf

src/main/java/com/coderby/myapp/attendance/dao/AttendanceMapper.xml, src/main/java/com/coderby/myapp/attendance/dao/IAttendanceRepository.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, target/classes/com/coderby/myapp/attendance/dao/AttendanceMapper.xml
#5 attendance행 select) 추가
ReportsService 휴가 반려 -> 승인할 때 selectAttend통해서 행 존재 확인 과정 추가
=> #5 AttendanceMapper, IAttendanceRepository에 selectAttend(학생의 특정날짜

src/main/java/com/coderby/myapp/attendance/controller/AttendScheduler.java, src/main/java/com/coderby/myapp/attendance/model/ReportsVO.java
#5 스케쥴러 작동 시간 변경 
reportsvo 멀티파트파일 필드 삭제
=> #5 스케쥴러 작동 시간 변경 

src/main/java/com/coderby/myapp/attendance/controller/AttendScheduler.java, src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/AttendanceMapper.xml, src/main/java/com/coderby/myapp/attendance/dao/IAttendanceRepository.java, src/main/java/com/coderby/myapp/attendance/service/AttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/IAttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/webapp/WEB-INF/views/attendance/studentAttend.jsp, target/classes/com/coderby/myapp/attendance/dao/AttendanceMapper.xml
=> ADFSFEFSFDAF

src/main/java/com/coderby/myapp/common/filter/LoginInterceptor.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
공통) servlet-context.xml에 interceptor설정 추가
=> 공통) LoginInterceptor 생성

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/dao/IReportsRepository.java, src/main/java/com/coderby/myapp/attendance/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/attendance/service/AttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/IReportsService.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/controller/StudentController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/java/com/coderby/myapp/classes/dao/IClassRepository.java, src/main/java/com/coderby/myapp/classes/service/ClassService.java, src/main/java/com/coderby/myapp/classes/service/IClassService.java, src/main/java/com/coderby/myapp/common/filter/LoginInterceptor.java, src/main/java/com/coderby/myapp/util/Pager.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/attendance/adminMainPage.jsp, src/main/webapp/WEB-INF/views/attendance/reportsDetail.jsp, src/main/webapp/WEB-INF/views/attendance/reportsList.jsp, src/main/webapp/WEB-INF/views/attendance/reportsWrite.jsp, src/main/webapp/WEB-INF/views/attendance/studentAttend.jsp, src/main/webapp/WEB-INF/views/attendance/studentReportsList.jsp, src/main/webapp/WEB-INF/views/board/list.jsp, src/main/webapp/WEB-INF/views/classes/classList.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/include/list.jsp, target/classes/com/coderby/myapp/attendance/dao/ReportsMapper.xml, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml
클래스 리스트 목록 조회/ 반 휴가 결재 목록 / 학생 휴가 목록 3개에 대한 페이징 처리 추가
list.jsp 사이드바 메뉴 url 주소 변경
=> 클래스 리스트 목록 조회/ 반 휴가 결재 목록 / 학생 휴가 목록 3개에 대한 페이징 처리 추가

src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/webapp/WEB-INF/views/attendance/adminMainPage.jsp, src/main/webapp/WEB-INF/views/attendance/reportsList.jsp, src/main/webapp/WEB-INF/views/attendance/studentAttend.jsp
휴가신청/휴가결재 로직 변경
반 근태 조회/ 학생 근태 조회 jsp 변경
=> 휴가신청/휴가결재 로직 변경

src/main/webapp/WEB-INF/views/attendance/reportsList.jsp, src/main/webapp/WEB-INF/views/attendance/studentReportsList.jsp, src/main/webapp/WEB-INF/views/classes/classList.jsp
테이블 들어가있는 페이지 행 어디든 눌렀을 때 url 요청으로 변경
=> 테이블 들어가있는 페이지 행 어디든 눌렀을 때 url 요청으로 변경

src/main/java/com/coderby/myapp/board/controller/BoardController.java, src/main/java/com/coderby/myapp/board/dao/IReplyRepository.java, src/main/java/com/coderby/myapp/board/dao/ReplyMapper.xml, src/main/java/com/coderby/myapp/board/service/BoardService.java, src/main/java/com/coderby/myapp/board/service/IBoardService.java, target/classes/com/coderby/myapp/board/dao/ReplyMapper.xml
게시물/댓글 수정,삭제 기능 => 본인이 작성한 글 아니면 수정 삭제 불가능하게 변경
BoardService, ReplyMapper에 selectReply(replyId) 메소드 추가
=> 게시물/댓글 수정,삭제 기능 => 본인이 작성한 글 아니면 수정 삭제 불가능하게 변경

src/main/java/com/coderby/myapp/attendance/controller/AttendScheduler.java, src/main/java/com/coderby/myapp/attendance/controller/AttendanceController.java, src/main/java/com/coderby/myapp/attendance/service/AttendanceService.java, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/java/com/coderby/myapp/board/controller/BoardController.java, src/main/webapp/WEB-INF/views/attendance/reportsDetail.jsp
휴가취소 now.getTime() < rep.getIntime().getTime() 부등호 변경
reportsDetail.jsp 휴가취소 버튼 상태가 대기일 때만 나타나게 변경
BoardController 댓글 수정 변경
필요없는 sysout문 삭제
휴가 취소 후 redirect경로 수정 (studentreportslistdefault)
=> 휴가취소 now.getTime() < rep.getIntime().getTime() 부등호 변경

src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/webapp/WEB-INF/views/attendance/reportsDetail.jsp
=> 휴가 상세조회 변경

src/main/java/com/coderby/myapp/attendance/dao/ReportsMapper.xml, src/main/java/com/coderby/myapp/attendance/service/ReportsService.java, src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/webapp/WEB-INF/views/attendance/reportsDetail.jsp, src/main/webapp/WEB-INF/views/attendance/reportsList.jsp, src/main/webapp/WEB-INF/views/classes/classList.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/attendance/dao/ReportsMapper.xml, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml
학생 휴가 목록/ 반 휴가 목록 mapper method order by rep_date 추가
=> 학생 휴가 목록/ 반 휴가 목록 mapper method order by rep_date 추가

src/main/java/com/coderby/myapp/board/controller/BoardController.java, src/main/java/com/coderby/myapp/board/dao/ReplyMapper.xml, src/main/webapp/WEB-INF/views/board/write.jsp, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/board/dao/ReplyMapper.xml
ReplyMapper insertReply 작성자 studentId로 변경
sectionList sectionDescription작성,수정 부분 textarea태그로 변경 BoardController insertReply메소드 replyVO파라미터에 session의 stdId set함
=> ReplyMapper insertReply 작성자 studentId로 변경

src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/java/com/coderby/myapp/classes/dao/ClassMapper.xml, src/main/java/com/coderby/myapp/classes/dao/IClassRepository.java, src/main/java/com/coderby/myapp/classes/model/SectionVO.java, src/main/java/com/coderby/myapp/classes/service/ClassService.java, src/main/java/com/coderby/myapp/classes/service/IClassService.java, src/main/webapp/WEB-INF/views/classes/sectionList.jsp, target/classes/com/coderby/myapp/classes/dao/ClassMapper.xml
=> 섹션 추가 중간 삽입 가능하게 변경

src/main/java/com/coderby/myapp/board/controller/BoardController.java, src/main/webapp/WEB-INF/resources/js/board.js, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/board/update.jsp
=> 게시물 수정 시 파일 삭제 기능 보완

src/main/java/com/coderby/myapp/classes/controller/ClassController.java, src/main/webapp/WEB-INF/views/classes/sectionList.jsp
firssectioninsert 핸들러 추가
jsp에 form 추가
=> 섹션이 아무것도 없을 때 추가할 수 있는 컨트롤러,form 추가
